# Generated by Django 5.2.16 on 2026-07-26 08:55

import apps.media_channel.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0016_seed_corporate_invoice_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertiserAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=32)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='advertiser_account', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='advertisers_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_advertiser_account',
            },
        ),
        migrations.CreateModel(
            name='MediaCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('operator', 'Operator media'), ('sponsored', 'Sponsored advertisement'), ('platform', 'HBT announcement')], max_length=16)),
                ('title_my', models.CharField(max_length=180)),
                ('title_en', models.CharField(blank=True, max_length=180)),
                ('body_my', models.TextField(blank=True)),
                ('body_en', models.TextField(blank=True)),
                ('placement', models.CharField(choices=[('media_feed', 'Media feed'), ('home', 'Home'), ('route_results', 'Route results'), ('operator_page', 'Operator page')], default='media_feed', max_length=24)),
                ('call_to_action_url', models.URLField(blank=True)),
                ('targeting', models.JSONField(blank=True, default=dict)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('frequency_cap_per_day', models.PositiveSmallIntegerField(default=3)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('payment_status', models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('submitted', 'Submitted for verification'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='not_required', max_length=24)),
                ('payment_reference', models.CharField(blank=True, max_length=160)),
                ('review_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('impressions', models.PositiveBigIntegerField(default=0)),
                ('clicks', models.PositiveBigIntegerField(default=0)),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='campaigns', to='media_channel.advertiseraccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_campaigns_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media_campaigns', to='tenancy.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='media_campaigns_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'media_campaign',
            },
        ),
        migrations.CreateModel(
            name='MediaCreative',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=8)),
                ('file', models.FileField(upload_to=apps.media_channel.models.creative_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('duration_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('poster_image', models.FileField(blank=True, upload_to=apps.media_channel.models.creative_upload_path)),
                ('processing_status', models.CharField(default='ready', max_length=16)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creatives', to='media_channel.mediacampaign')),
            ],
            options={
                'db_table': 'media_creative',
            },
        ),
        migrations.AddIndex(
            model_name='mediacampaign',
            index=models.Index(fields=['status', 'starts_at', 'ends_at'], name='media_campaign_delivery_idx'),
        ),
        migrations.AddIndex(
            model_name='mediacampaign',
            index=models.Index(fields=['organization', 'status'], name='media_campaign_org_idx'),
        ),
    ]
