# Generated by Django 5.2.16 on 2026-07-25 07:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('scheduling', '0002_trip_arrived_at_trip_boarding_started_at_and_more'),
        ('tenancy', '0011_seed_cargo_finance_operations_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=32)),
                ('nrc_normalized', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_contacts', to='tenancy.organization')),
            ],
            options={
                'db_table': 'cargo_contact',
            },
        ),
        migrations.CreateModel(
            name='CargoPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('max_declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('prohibited_categories', models.JSONField(blank=True, default=list)),
                ('require_sender_nrc', models.BooleanField(default=False)),
                ('require_receiver_nrc', models.BooleanField(default=False)),
                ('liability_text', models.TextField(blank=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_policy', to='tenancy.organization')),
            ],
            options={
                'db_table': 'cargo_policy',
            },
        ),
        migrations.CreateModel(
            name='CargoShipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment_number', models.CharField(max_length=64)),
                ('tracking_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('accepted', 'Accepted'), ('assigned', 'Assigned'), ('loaded', 'Loaded'), ('in_transit', 'In transit'), ('arrived', 'Arrived'), ('ready_pickup', 'Ready for pickup'), ('handed_over', 'Handed over'), ('refused', 'Refused'), ('cancelled', 'Cancelled'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('returned', 'Returned')], default='draft', max_length=16)),
                ('item_category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('piece_count', models.PositiveIntegerField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('weight_source', models.CharField(blank=True, choices=[('declared', 'Declared'), ('measured', 'Measured')], max_length=12)),
                ('declared_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('pricing_method', models.CharField(choices=[('manual', 'Manual charge'), ('per_kg', 'Per kilogram')], max_length=12)),
                ('rate_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('manual_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('additional_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_charge', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MMK', max_length=3)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('expected_pickup_date', models.DateField(blank=True, null=True)),
                ('client_request_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accepted_cargo_shipments', to=settings.AUTH_USER_MODEL)),
                ('assigned_trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargo_shipments', to='scheduling.trip')),
                ('destination_terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination_cargo_shipments', to='locations.companyterminaloperation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_shipments', to='tenancy.organization')),
                ('origin_terminal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin_cargo_shipments', to='locations.companyterminaloperation')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_shipments', to='cargo.cargocontact')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_shipments', to='cargo.cargocontact')),
            ],
            options={
                'db_table': 'cargo_shipment',
            },
        ),
        migrations.CreateModel(
            name='CargoCustodyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(choices=[('draft', 'Draft'), ('accepted', 'Accepted'), ('assigned', 'Assigned'), ('loaded', 'Loaded'), ('in_transit', 'In transit'), ('arrived', 'Arrived'), ('ready_pickup', 'Ready for pickup'), ('handed_over', 'Handed over'), ('refused', 'Refused'), ('cancelled', 'Cancelled'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('returned', 'Returned')], max_length=16)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('accepted', 'Accepted'), ('assigned', 'Assigned'), ('loaded', 'Loaded'), ('in_transit', 'In transit'), ('arrived', 'Arrived'), ('ready_pickup', 'Ready for pickup'), ('handed_over', 'Handed over'), ('refused', 'Refused'), ('cancelled', 'Cancelled'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('returned', 'Returned')], max_length=16)),
                ('occurred_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('offline', models.BooleanField(default=False)),
                ('client_event_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('terminal_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.companyterminaloperation')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scheduling.trip')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custody_events', to='cargo.cargoshipment')),
            ],
            options={
                'db_table': 'cargo_custody_event',
                'ordering': ('occurred_at', 'created_at'),
            },
        ),
        migrations.AddIndex(
            model_name='cargocontact',
            index=models.Index(fields=['organization', 'phone_number'], name='cargo_contact_phone_idx'),
        ),
        migrations.AddConstraint(
            model_name='cargocontact',
            constraint=models.UniqueConstraint(fields=('organization', 'contact_code'), name='unique_cargo_contact_code_per_org'),
        ),
        migrations.AddIndex(
            model_name='cargoshipment',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='cargo_org_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='cargoshipment',
            constraint=models.UniqueConstraint(fields=('organization', 'shipment_number'), name='unique_cargo_shipment_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='cargoshipment',
            constraint=models.CheckConstraint(condition=models.Q(('piece_count__gt', 0)), name='cargo_piece_count_positive'),
        ),
    ]
