# Generated by Django 5.2.16 on 2026-07-25 12:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
        ('locations', '0001_initial'),
        ('tenancy', '0012_seed_payment_integration_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargocontact',
            name='contact_type',
            field=models.CharField(choices=[('individual', 'Individual'), ('business', 'Business customer'), ('agent', 'Agent')], default='individual', max_length=16),
        ),
        migrations.AddField(
            model_name='cargocontact',
            name='identity_missing_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cargocontact',
            name='identity_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cargocontact',
            name='identity_type',
            field=models.CharField(choices=[('nrc', 'Myanmar NRC'), ('passport', 'Passport'), ('other', 'Other identity'), ('not_provided', 'Not provided')], default='not_provided', max_length=16),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='acceptance_channel',
            field=models.CharField(choices=[('counter', 'Counter'), ('terminal', 'Terminal cargo desk'), ('roadside', 'Roadside'), ('conductor', 'Conductor'), ('agent', 'Agent')], default='counter', max_length=16),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='accepting_counter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_cargo_shipments', to='locations.salescounter'),
        ),
        migrations.CreateModel(
            name='CargoCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=150)),
                ('name_myanmar', models.CharField(blank=True, max_length=150)),
                ('default_pricing_method', models.CharField(choices=[('manual', 'Manual charge'), ('per_kg', 'Per kilogram')], default='manual', max_length=12)),
                ('default_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('prohibited', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_categories', to='tenancy.organization')),
            ],
            options={
                'db_table': 'cargo_category',
            },
        ),
        migrations.CreateModel(
            name='CargoChargeLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField()),
                ('label', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('charge', 'Charge'), ('discount', 'Discount')], max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_lines', to='cargo.cargoshipment')),
            ],
            options={
                'db_table': 'cargo_charge_line',
                'ordering': ('sequence', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='CargoItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_snapshot', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('pricing_method', models.CharField(choices=[('manual', 'Manual charge'), ('per_kg', 'Per kilogram')], max_length=12)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rate_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('manual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notice', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cargo.cargocategory')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='cargo.cargoshipment')),
            ],
            options={
                'db_table': 'cargo_item',
            },
        ),
        migrations.AddConstraint(
            model_name='cargocategory',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_cargo_category_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='cargochargeline',
            constraint=models.UniqueConstraint(fields=('shipment', 'code'), name='unique_cargo_charge_code_per_shipment'),
        ),
        migrations.AddConstraint(
            model_name='cargochargeline',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='cargo_charge_line_amount_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='cargoitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='cargo_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='cargoitem',
            constraint=models.CheckConstraint(condition=models.Q(('base_amount__gte', 0)), name='cargo_item_base_amount_nonnegative'),
        ),
    ]
