# Generated by Django 5.2.16 on 2026-07-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_cargocontact_contact_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargocustodyevent',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cargocustodyevent',
            name='verification_method',
            field=models.CharField(blank=True, choices=[('', 'Not applicable'), ('qr', 'Shipment QR'), ('phone', 'Phone confirmation'), ('otp', 'One-time code'), ('identity', 'Identity check'), ('delegated', 'Delegated pickup authorization')], max_length=16),
        ),
        migrations.AddField(
            model_name='cargocustodyevent',
            name='verification_reference_masked',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='cargopolicy',
            name='max_height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cargopolicy',
            name='max_length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cargopolicy',
            name='max_width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='acceptance_device_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='actual_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='inspection_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='liability_acknowledged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='packaging_condition',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='pickup_location_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
