# Generated by Django 5.2.16 on 2026-07-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_cargocustodyevent_recipient_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargocategory',
            name='default_pricing_method',
            field=models.CharField(choices=[('manual', 'Manual total'), ('per_kg', 'Per kilogram'), ('itemized', 'Per item / station breakdown')], default='manual', max_length=12),
        ),
        migrations.AlterField(
            model_name='cargochargeline',
            name='kind',
            field=models.CharField(choices=[('charge', 'Charge'), ('discount', 'Discount'), ('allocation', 'Internal terminal/partner allocation')], max_length=12),
        ),
        migrations.AlterField(
            model_name='cargoitem',
            name='pricing_method',
            field=models.CharField(choices=[('manual', 'Manual total'), ('per_kg', 'Per kilogram'), ('itemized', 'Per item / station breakdown'), ('mixed', 'Mixed pricing')], max_length=12),
        ),
        migrations.AlterField(
            model_name='cargoshipment',
            name='pricing_method',
            field=models.CharField(choices=[('manual', 'Manual total'), ('per_kg', 'Per kilogram'), ('itemized', 'Per item / station breakdown'), ('mixed', 'Mixed pricing')], max_length=12),
        ),
    ]
