# Generated by Django 5.2.16 on 2026-07-25 14:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0004_alter_cargocategory_default_pricing_method_and_more'),
        ('tenancy', '0013_seed_cargo_roadside_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cargochargeline',
            name='payout_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cargochargeline',
            name='payout_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cargochargeline',
            name='payout_paid_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_cargo_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargochargeline',
            name='payout_recipient_contact',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='cargochargeline',
            name='payout_recipient_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='cargoitem',
            name='manual_pricing_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cargoitem',
            name='priced_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cargoitem',
            name='priced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='priced_cargo_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cargoitem',
            name='pricing_rule_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='cargoshipment',
            name='manual_pricing_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cargocategory',
            name='default_pricing_method',
            field=models.CharField(choices=[('manual', 'Manual total'), ('per_kg', 'Per kilogram'), ('itemized', 'Per item / station breakdown'), ('tiered_kg', 'Base weight plus decimal excess rate')], default='manual', max_length=12),
        ),
        migrations.AlterField(
            model_name='cargoitem',
            name='pricing_method',
            field=models.CharField(choices=[('manual', 'Manual total'), ('per_kg', 'Per kilogram'), ('itemized', 'Per item / station breakdown'), ('tiered_kg', 'Base weight plus decimal excess rate'), ('mixed', 'Mixed pricing')], max_length=12),
        ),
        migrations.AlterField(
            model_name='cargoshipment',
            name='pricing_method',
            field=models.CharField(choices=[('manual', 'Manual total'), ('per_kg', 'Per kilogram'), ('itemized', 'Per item / station breakdown'), ('tiered_kg', 'Base weight plus decimal excess rate'), ('mixed', 'Mixed pricing')], max_length=12),
        ),
        migrations.CreateModel(
            name='CargoPricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=150)),
                ('method', models.CharField(choices=[('tiered_kg', 'Base weight plus decimal excess rate')], default='tiered_kg', max_length=16)),
                ('base_weight_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('excess_rate_per_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pricing_rules', to='cargo.cargocategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_cargo_pricing_rules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo_pricing_rules', to='tenancy.organization')),
            ],
            options={
                'db_table': 'cargo_pricing_rule',
            },
        ),
        migrations.AddField(
            model_name='cargoitem',
            name='pricing_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cargo.cargopricingrule'),
        ),
        migrations.AddConstraint(
            model_name='cargopricingrule',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_cargo_pricing_rule_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='cargopricingrule',
            constraint=models.CheckConstraint(condition=models.Q(('base_weight_kg__gt', 0), ('base_price__gte', 0), ('excess_rate_per_kg__gte', 0)), name='cargo_pricing_rule_values_valid'),
        ),
    ]
