# Generated by Django 5.2.16 on 2026-07-26 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0005_cargochargeline_payout_paid_and_more'),
        ('reference_data', '0002_seed_nrc_reference_v1'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargocontact',
            name='encrypted_nrc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cargocontact',
            name='nrc_blind_index',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='cargocontact',
            name='nrc_citizenship_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargo_contacts', to='reference_data.nrccitizenshiptype'),
        ),
        migrations.AddField(
            model_name='cargocontact',
            name='nrc_serial',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='cargocontact',
            name='nrc_state_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargo_contacts', to='reference_data.nrcstateregion'),
        ),
        migrations.AddField(
            model_name='cargocontact',
            name='nrc_township',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargo_contacts', to='reference_data.nrctownship'),
        ),
    ]
