# Generated by Django 5.2.16 on 2026-07-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0006_cargocontact_encrypted_nrc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargocontact',
            name='nrc_review_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cargocontact',
            name='nrc_verification_status',
            field=models.CharField(default='not_provided', max_length=16),
        ),
    ]
