# Generated by Django 5.2.16 on 2026-07-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0008_backfill_encrypted_nrc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargocontact',
            name='nrc_normalized',
        ),
    ]
