# Generated by Django 5.2.16 on 2026-07-25 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
        ('scheduling', '0002_trip_arrived_at_trip_boarding_started_at_and_more'),
        ('tenancy', '0010_seed_passenger_sales_boarding_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seat_identifier_snapshot', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('held', 'Held'), ('reserved', 'Reserved'), ('confirmed', 'Confirmed'), ('released', 'Released'), ('expired', 'Expired'), ('completed', 'Completed')], default='held', max_length=12)),
            ],
            options={
                'db_table': 'bookings_seat_reservation',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_number', models.CharField(max_length=50)),
                ('booking_type', models.CharField(choices=[('individual', 'Individual'), ('group', 'Group'), ('family', 'Family'), ('corporate', 'Corporate'), ('agent', 'Agent')], max_length=16)),
                ('channel', models.CharField(choices=[('counter', 'Counter'), ('agent', 'Agent'), ('mobile', 'Mobile app'), ('website', 'Website'), ('call_center', 'Call center'), ('api', 'API integration'), ('roadside', 'Roadside')], max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reserved', 'Reserved'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(max_length=32)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('authorization_reference', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('client_request_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_bookings', to=settings.AUTH_USER_MODEL)),
                ('dropoff_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dropoff_bookings', to='network.routestop')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='tenancy.organization')),
                ('pickup_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pickup_bookings', to='network.routestop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='scheduling.trip')),
            ],
            options={
                'db_table': 'bookings_booking',
            },
        ),
        migrations.CreateModel(
            name='BookingPassenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passenger_items', to='bookings.booking')),
            ],
            options={
                'db_table': 'bookings_booking_passenger',
            },
        ),
    ]
