# Generated by Django 5.2.16 on 2026-07-25 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('fleet', '0001_initial'),
        ('passengers', '0001_initial'),
        ('scheduling', '0002_trip_arrived_at_trip_boarding_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpassenger',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_items', to='passengers.passenger'),
        ),
        migrations.AddField(
            model_name='seatreservation',
            name='booking_passenger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='seat_reservation', to='bookings.bookingpassenger'),
        ),
        migrations.AddField(
            model_name='seatreservation',
            name='seat_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_reservations', to='fleet.layoutposition'),
        ),
        migrations.AddField(
            model_name='seatreservation',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_reservations', to='scheduling.trip'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='booking_org_status_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=models.UniqueConstraint(fields=('organization', 'booking_number'), name='unique_booking_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='bookingpassenger',
            constraint=models.UniqueConstraint(fields=('booking', 'passenger'), name='unique_passenger_per_booking'),
        ),
        migrations.AddConstraint(
            model_name='seatreservation',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['held', 'reserved', 'confirmed'])), fields=('trip', 'seat_position'), name='unique_active_seat_per_trip'),
        ),
    ]
