# Generated by Django 5.2.16 on 2026-07-25 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('fleet', '0002_vehicle_cargo_weight_capacity_kg'),
        ('scheduling', '0002_trip_arrived_at_trip_boarding_started_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seatreservation',
            name='unique_active_seat_per_trip',
        ),
        migrations.AddField(
            model_name='booking',
            name='customer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='seatreservation',
            name='dropoff_sequence',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='seatreservation',
            name='pickup_sequence',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='seatreservation',
            constraint=models.CheckConstraint(condition=models.Q(('dropoff_sequence__gt', models.F('pickup_sequence'))), name='seat_reservation_segment_forward'),
        ),
    ]
