# Generated by Django 5.2.16 on 2026-07-26 07:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_seatreservation_unique_active_seat_per_trip_and_more'),
        ('fares', '0001_initial'),
        ('tenancy', '0015_seed_fare_feedback_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateCustomer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField()),
                ('legal_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('billing_address', models.TextField(blank=True)),
                ('tax_identifier', models.CharField(blank=True, max_length=100)),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=7)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corporate_customers', to='tenancy.organization')),
            ],
            options={
                'db_table': 'bookings_corporate_customer',
            },
        ),
        migrations.CreateModel(
            name='CorporateBookingApproval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='submitted', max_length=16)),
                ('submitted_at', models.DateTimeField()),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='corporate_approval', to='bookings.booking')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corporate_bookings_decided', to=settings.AUTH_USER_MODEL)),
                ('fare_quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='corporate_approval', to='fares.farequote')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corporate_bookings_requested', to=settings.AUTH_USER_MODEL)),
                ('corporate_customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booking_approvals', to='bookings.corporatecustomer')),
            ],
            options={
                'db_table': 'bookings_corporate_approval',
            },
        ),
        migrations.CreateModel(
            name='CorporateCustomerMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('revoked', 'Revoked')], default='invited', max_length=16)),
                ('can_request', models.BooleanField(default=True)),
                ('can_approve', models.BooleanField(default=False)),
                ('corporate_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='bookings.corporatecustomer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corporate_customer_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings_corporate_customer_member',
            },
        ),
        migrations.CreateModel(
            name='CorporateInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('paid', 'Paid'), ('void', 'Void'), ('overdue', 'Overdue')], default='issued', max_length=16)),
                ('currency', models.CharField(default='MMK', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_at', models.DateTimeField()),
                ('issued_at', models.DateTimeField()),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='bookings.corporatebookingapproval')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices_issued', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corporate_invoices', to='tenancy.organization')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='replacements', to='bookings.corporateinvoice')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices_voided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings_corporate_invoice',
            },
        ),
        migrations.AddConstraint(
            model_name='corporatecustomer',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_corporate_customer_code'),
        ),
        migrations.AddConstraint(
            model_name='corporatecustomermember',
            constraint=models.UniqueConstraint(fields=('corporate_customer', 'user'), name='unique_corporate_customer_user'),
        ),
        migrations.AddConstraint(
            model_name='corporateinvoice',
            constraint=models.UniqueConstraint(fields=('organization', 'invoice_number'), name='unique_corporate_invoice_number'),
        ),
    ]
