# Generated by Django 5.2.16 on 2026-07-31 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_corporatecustomer_corporatebookingapproval_and_more'),
        ('fleet', '0002_vehicle_cargo_weight_capacity_kg'),
        ('scheduling', '0002_trip_arrived_at_trip_boarding_started_at_and_more'),
        ('tenancy', '0019_seed_provider_payment_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatLock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('held_by_device_id', models.CharField(blank=True, max_length=64)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('held', 'Held'), ('released', 'Released'), ('expired', 'Expired'), ('consumed', 'Consumed')], default='held', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('held_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seat_locks', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_locks', to='tenancy.organization')),
                ('seat_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_seat_locks', to='fleet.layoutposition')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_locks', to='scheduling.trip')),
            ],
            options={
                'db_table': 'bookings_seat_lock',
                'indexes': [models.Index(fields=['status', 'expires_at'], name='seat_lock_status_expiry_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'held')), fields=('trip', 'seat_position'), name='uniq_active_seat_lock_per_trip_seat')],
            },
        ),
    ]
