# Generated by Django 5.2.16 on 2026-07-25 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('fleet', '0001_initial'),
        ('passengers', '0001_initial'),
        ('scheduling', '0002_trip_arrived_at_trip_boarding_started_at_and_more'),
        ('tenancy', '0010_seed_passenger_sales_boarding_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.CharField(max_length=64)),
                ('ticket_type', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('staff', 'Staff'), ('complimentary', 'Complimentary'), ('child', 'Child'), ('corporate', 'Corporate'), ('manual', 'Manual'), ('electronic', 'Electronic')], default='electronic', max_length=16)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('validated', 'Validated'), ('boarded', 'Boarded'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('reissued', 'Reissued'), ('archived', 'Archived')], default='issued', max_length=16)),
                ('validation_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fare_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='MMK', max_length=3)),
                ('issuing_channel', models.CharField(max_length=16)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='bookings.booking')),
                ('booking_passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='bookings.bookingpassenger')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_tickets', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tenancy.organization')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='passengers.passenger')),
                ('seat_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='fleet.layoutposition')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='scheduling.trip')),
            ],
            options={
                'db_table': 'ticketing_ticket',
                'constraints': [models.UniqueConstraint(fields=('organization', 'ticket_number'), name='unique_ticket_number_per_org'), models.UniqueConstraint(condition=models.Q(('status__in', ['issued', 'validated', 'boarded', 'completed'])), fields=('booking_passenger',), name='unique_active_ticket_per_booking_passenger'), models.CheckConstraint(condition=models.Q(('fare_amount__gte', 0), ('discount_amount__gte', 0), ('tax_amount__gte', 0), ('service_charge__gte', 0), ('total_amount__gte', 0)), name='ticket_fare_values_nonnegative')],
            },
        ),
    ]
