# Generated by Django 5.2.16 on 2026-08-01 05:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_seatlock'),
        ('fleet', '0002_vehicle_cargo_weight_capacity_kg'),
        ('passengers', '0007_remove_passenger_national_id_and_more'),
        ('scheduling', '0002_trip_arrived_at_trip_boarding_started_at_and_more'),
        ('tenancy', '0019_seed_provider_payment_permissions'),
        ('ticketing', '0002_ticket_replacement_of_ticket_revocation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['organization', 'status', 'issued_at'], name='ticket_org_status_issued_idx'),
        ),
    ]
