# Generated by Django 5.2.16 on 2026-07-26 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NRCCitizenshipType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_en', models.CharField(max_length=4, unique=True)),
                ('code_mm', models.CharField(max_length=32, unique=True)),
                ('name_en', models.CharField(max_length=120)),
                ('name_mm', models.CharField(max_length=120)),
                ('source_version', models.CharField(default='mm-nrc-2021', max_length=32)),
                ('verification_status', models.CharField(default='community', max_length=16)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'reference_nrc_citizenship_type',
                'ordering': ('code_en',),
            },
        ),
        migrations.CreateModel(
            name='NRCStateRegion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.PositiveSmallIntegerField(unique=True)),
                ('number_mm', models.CharField(max_length=4)),
                ('name_en', models.CharField(max_length=100)),
                ('name_mm', models.CharField(max_length=100)),
                ('source_version', models.CharField(default='mm-nrc-2021', max_length=32)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'reference_nrc_state_region',
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='NRCTownship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_en', models.CharField(max_length=32)),
                ('code_mm', models.CharField(max_length=16)),
                ('name_en', models.CharField(max_length=160)),
                ('name_mm', models.CharField(max_length=160)),
                ('name_aliases', models.JSONField(blank=True, default=list)),
                ('source_ids', models.JSONField(blank=True, default=list)),
                ('source_version', models.CharField(default='mm-nrc-2021', max_length=32)),
                ('verification_status', models.CharField(default='community', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('state_region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='townships', to='reference_data.nrcstateregion')),
            ],
            options={
                'db_table': 'reference_nrc_township',
                'ordering': ('state_region__code', 'code_en'),
                'indexes': [models.Index(fields=['state_region', 'active'], name='nrc_township_state_active_idx')],
                'constraints': [models.UniqueConstraint(fields=('state_region', 'code_en'), name='unique_nrc_township_code_per_state')],
            },
        ),
    ]
