# Generated by Django 5.2.16 on 2026-07-26 04:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0013_seed_cargo_roadside_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=100)),
                ('event_key', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('booking', 'Booking'), ('ticket', 'Ticket'), ('payment', 'Payment'), ('cargo', 'Cargo'), ('trip', 'Trip'), ('system', 'System'), ('security', 'Security')], max_length=24)),
                ('category', models.CharField(choices=[('information', 'Information'), ('action_required', 'Action required'), ('payment_verification', 'Payment verification'), ('trip_operation', 'Trip operation'), ('urgent_exception', 'Urgent exception')], max_length=32)),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('push', 'Push')], max_length=16)),
                ('language', models.CharField(default='my', max_length=10)),
                ('title', models.CharField(max_length=160)),
                ('body', models.CharField(max_length=500)),
                ('data', models.JSONField(default=dict)),
                ('deep_link', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('created', 'Created'), ('queued', 'Queued'), ('processing', 'Processing'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='created', max_length=16)),
                ('available_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tenancy.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_notification',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField()),
                ('device_id', models.UUIDField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(max_length=24)),
                ('provider_reference', models.CharField(blank=True, max_length=200)),
                ('failure_reason', models.CharField(blank=True, max_length=500)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='notifications.notification')),
            ],
            options={
                'db_table': 'notification_delivery_attempt',
            },
        ),
        migrations.CreateModel(
            name='PendingWorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_key', models.CharField(max_length=200)),
                ('work_type', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=160)),
                ('deep_link', models.CharField(max_length=500)),
                ('priority', models.CharField(default='normal', max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_work_items', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_work_items', to='tenancy.organization')),
            ],
            options={
                'db_table': 'notification_pending_work',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'channel', 'read_at', 'created_at'], name='notification_inbox_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'available_at'], name='notification_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(fields=('recipient', 'event_key', 'channel'), name='unique_notification_event_channel'),
        ),
        migrations.AddConstraint(
            model_name='deliveryattempt',
            constraint=models.UniqueConstraint(fields=('notification', 'attempt_number', 'device_id'), name='unique_notification_delivery_attempt'),
        ),
        migrations.AddIndex(
            model_name='pendingworkitem',
            index=models.Index(fields=['assignee', 'status', 'created_at'], name='pending_work_assignee_idx'),
        ),
        migrations.AddConstraint(
            model_name='pendingworkitem',
            constraint=models.UniqueConstraint(fields=('assignee', 'event_key', 'work_type'), name='unique_pending_work_event'),
        ),
    ]
