# Generated by Django 5.2.16 on 2026-07-25 07:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scheduling', '0002_trip_arrived_at_trip_boarding_started_at_and_more'),
        ('tenancy', '0011_seed_cargo_finance_operations_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineOperationReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_operation_id', models.UUIDField(unique=True)),
                ('operation_type', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('request_hash', models.CharField(max_length=64)),
                ('result_snapshot', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('synchronized_at', models.DateTimeField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_receipts', to='tenancy.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operations_offline_receipt',
            },
        ),
        migrations.CreateModel(
            name='PrintDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('ticket', 'Ticket'), ('payment_slip', 'Payment slip'), ('cargo_receipt', 'Cargo receipt'), ('cargo_label', 'Cargo label'), ('trip_manifest', 'Trip manifest'), ('settlement', 'Settlement')], max_length=20)),
                ('resource_type', models.CharField(max_length=50)),
                ('resource_id', models.UUIDField()),
                ('payload', models.JSONField()),
                ('template_version', models.PositiveIntegerField(default=1)),
                ('client_request_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('print_count', models.PositiveIntegerField(default=0)),
                ('last_printed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_documents', to='tenancy.organization')),
            ],
            options={
                'db_table': 'operations_print_document',
            },
        ),
        migrations.CreateModel(
            name='TripClosing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passenger_count', models.PositiveIntegerField()),
                ('boarded_count', models.PositiveIntegerField()),
                ('cargo_count', models.PositiveIntegerField()),
                ('cargo_handed_over_count', models.PositiveIntegerField()),
                ('unresolved_exception_count', models.PositiveIntegerField()),
                ('summary_snapshot', models.JSONField()),
                ('closed_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('closed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_closings', to='tenancy.organization')),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='closing', to='scheduling.trip')),
            ],
            options={
                'db_table': 'operations_trip_closing',
            },
        ),
        migrations.CreateModel(
            name='CashSettlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('settlement_number', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('verified', 'Verified'), ('approved', 'Approved'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('actual_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('difference_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('difference_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_settlements', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_settlements', to='tenancy.organization')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_settlements', to=settings.AUTH_USER_MODEL)),
                ('trip', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cash_settlement', to='scheduling.trip')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_settlements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'operations_cash_settlement',
                'constraints': [models.UniqueConstraint(fields=('organization', 'settlement_number'), name='unique_settlement_number_per_org')],
            },
        ),
    ]
