# Generated by Django 5.2.16 on 2026-07-26 15:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        ('tenancy', '0019_seed_provider_payment_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('connection_type', models.CharField(choices=[('bluetooth', 'Bluetooth'), ('network', 'Network'), ('usb', 'USB')], max_length=16)),
                ('paper_width_mm', models.PositiveSmallIntegerField(default=80)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('character_encoding', models.CharField(default='utf-8', max_length=32)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printer_profiles', to='tenancy.organization')),
            ],
            options={
                'db_table': 'operations_printer_profile',
            },
        ),
        migrations.CreateModel(
            name='PrintAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_installation_id', models.UUIDField(blank=True, null=True)),
                ('client_attempt_id', models.UUIDField(unique=True)),
                ('status', models.CharField(choices=[('printed', 'Printed'), ('failed', 'Failed')], max_length=12)),
                ('offline', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, max_length=500)),
                ('occurred_at', models.DateTimeField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='operations.printdocument')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_attempts', to='tenancy.organization')),
                ('printed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('printer_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.printerprofile')),
            ],
            options={
                'db_table': 'operations_print_attempt',
            },
        ),
        migrations.CreateModel(
            name='PrintTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('ticket', 'Ticket'), ('payment_slip', 'Payment slip'), ('cargo_receipt', 'Cargo receipt'), ('cargo_label', 'Cargo label'), ('trip_manifest', 'Trip manifest'), ('settlement', 'Settlement')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('version', models.PositiveIntegerField(default=1)),
                ('paper_width_mm', models.PositiveSmallIntegerField(default=80)),
                ('definition', models.JSONField(default=dict)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='print_templates', to='tenancy.organization')),
            ],
            options={
                'db_table': 'operations_print_template',
            },
        ),
        migrations.AddConstraint(
            model_name='printerprofile',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_printer_profile_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='printerprofile',
            constraint=models.CheckConstraint(condition=models.Q(('paper_width_mm__in', [58, 80])), name='printer_paper_width_supported'),
        ),
        migrations.AddIndex(
            model_name='printattempt',
            index=models.Index(fields=['organization', 'occurred_at'], name='print_attempt_org_time_idx'),
        ),
        migrations.AddConstraint(
            model_name='printattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('failure_reason', ''), ('status', 'printed')), ('status', 'failed'), _connector='OR'), name='print_failure_reason_only_on_failure'),
        ),
        migrations.AddConstraint(
            model_name='printtemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'document_type', 'version'), name='unique_print_template_version_per_org'),
        ),
        migrations.AddConstraint(
            model_name='printtemplate',
            constraint=models.CheckConstraint(condition=models.Q(('paper_width_mm__in', [58, 80])), name='template_paper_width_supported'),
        ),
    ]
