# Generated by Django 5.2.16 on 2026-07-26 07:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0003_remove_seatreservation_unique_active_seat_per_trip_and_more'),
        ('network', '0001_initial'),
        ('scheduling', '0002_trip_arrived_at_trip_boarding_started_at_and_more'),
        ('tenancy', '0014_seed_notification_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FareQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('quoted', 'Quoted'), ('locked', 'Locked'), ('expired', 'Expired'), ('superseded', 'Superseded')], default='quoted', max_length=16)),
                ('currency', models.CharField(default='MMK', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('expires_at', models.DateTimeField()),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot', models.JSONField(default=dict)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fare_quotes', to='bookings.booking')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fare_quotes_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fares_quote',
            },
        ),
        migrations.CreateModel(
            name='FareRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=160)),
                ('vehicle_category', models.CharField(blank=True, max_length=32)),
                ('booking_channel', models.CharField(blank=True, max_length=16)),
                ('currency', models.CharField(default='MMK', max_length=3)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0, max_digits=7)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('effective_from', models.DateTimeField()),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fare_rules_created', to=settings.AUTH_USER_MODEL)),
                ('dropoff_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fare_rules_to', to='network.routestop')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fare_rules', to='tenancy.organization')),
                ('pickup_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fare_rules_from', to='network.routestop')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fare_rules', to='network.route')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fare_rules', to='scheduling.schedule')),
            ],
            options={
                'db_table': 'fares_rule',
            },
        ),
        migrations.CreateModel(
            name='FareQuoteLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_fare', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('overridden', models.BooleanField(default=False)),
                ('override_reason', models.TextField(blank=True)),
                ('rule_snapshot', models.JSONField(default=dict)),
                ('booking_passenger', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fare_quote_lines', to='bookings.bookingpassenger')),
                ('overridden_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fare_lines_overridden', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='fares.farequote')),
                ('fare_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_lines', to='fares.farerule')),
            ],
            options={
                'db_table': 'fares_quote_line',
            },
        ),
        migrations.AddConstraint(
            model_name='farequote',
            constraint=models.UniqueConstraint(fields=('booking', 'version'), name='unique_booking_fare_version'),
        ),
        migrations.AddConstraint(
            model_name='farequote',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'locked')), fields=('booking',), name='unique_locked_fare_quote'),
        ),
        migrations.AddConstraint(
            model_name='farerule',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_fare_rule_code'),
        ),
        migrations.AddConstraint(
            model_name='farerule',
            constraint=models.CheckConstraint(condition=models.Q(('base_fare__gte', 0)), name='fare_rule_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='farerule',
            constraint=models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0)), name='fare_rule_tax_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='farequoteline',
            constraint=models.UniqueConstraint(fields=('quote', 'booking_passenger'), name='unique_quote_passenger_line'),
        ),
    ]
