# Generated by Django 5.2.16 on 2026-07-26 08:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fares', '0001_initial'),
        ('network', '0001_initial'),
        ('scheduling', '0002_trip_arrived_at_trip_boarding_started_at_and_more'),
        ('tenancy', '0016_seed_corporate_invoice_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farequote',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=64)),
                ('name_my', models.CharField(max_length=160)),
                ('name_en', models.CharField(blank=True, max_length=160)),
                ('description_my', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('coupon_code', models.CharField(blank=True, max_length=64)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed amount'), ('buy_x_get_y', 'Buy X get Y')], max_length=16)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=14)),
                ('maximum_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('minimum_passengers', models.PositiveSmallIntegerField(default=1)),
                ('discounted_passenger_count', models.PositiveSmallIntegerField(default=0)),
                ('booking_channel', models.CharField(blank=True, max_length=16)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('total_usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('per_account_limit', models.PositiveIntegerField(default=1)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('stackable', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions_created', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='tenancy.organization')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='network.route')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='scheduling.schedule')),
            ],
            options={
                'db_table': 'fares_promotion',
            },
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon_code', models.CharField(max_length=64)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='coupon_redemption', to='fares.farequote')),
                ('promotion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='fares.promotion')),
            ],
            options={
                'db_table': 'fares_coupon_redemption',
            },
        ),
        migrations.AddField(
            model_name='farequote',
            name='applied_promotion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fare_quotes', to='fares.promotion'),
        ),
        migrations.AddIndex(
            model_name='promotion',
            index=models.Index(fields=['organization', 'active', 'starts_at', 'ends_at'], name='promotion_active_window_idx'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_promotion_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.UniqueConstraint(condition=models.Q(('coupon_code', ''), _negated=True), fields=('organization', 'coupon_code'), name='unique_coupon_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('discount_value__gte', 0)), name='promotion_discount_nonnegative'),
        ),
        migrations.AddIndex(
            model_name='couponredemption',
            index=models.Index(fields=['promotion', 'account'], name='coupon_promotion_account_idx'),
        ),
    ]
