from django.urls import path

from .views import (
    PaymentAccountApproveView,
    PaymentAccountDetailView,
    PaymentAccountListCreateView,
    PaymentAccountVersionCreateView,
    PaymentDecisionView,
    PaymentListCreateView,
    PrivatePaymentDownloadView,
    PrivatePaymentUploadView,
    SelfPaymentCreateView,
    SelfPaymentEvidenceUploadView,
    SelfPaymentOptionsView,
    RefundCompleteView,
    RefundDecisionView,
    RefundListCreateView,
    RefundPaidView,
    RefundPolicyView,
    InvoiceAllocationListView,
    PaymentConnectorDetailView,
    PaymentConnectorListCreateView,
    PaymentConnectorTestView,
    PaymentConnectorWebhookView,
    ProviderPaymentIntentCreateView,
    PaymentConnectorDisableView,
    PaymentConnectorRotateView,
)

urlpatterns = [
    path(
        "passenger/bookings/<uuid:booking_id>/payment-options/",
        SelfPaymentOptionsView.as_view(),
    ),
    path(
        "passenger/bookings/<uuid:booking_id>/payment-evidence/",
        SelfPaymentEvidenceUploadView.as_view(),
    ),
    path(
        "passenger/bookings/<uuid:booking_id>/payments/",
        SelfPaymentCreateView.as_view(),
    ),
    path(
        "organizations/<uuid:organization_id>/payment-accounts/",
        PaymentAccountListCreateView.as_view(),
    ),
    path(
        "organizations/<uuid:organization_id>/payment-accounts/<uuid:pk>/",
        PaymentAccountDetailView.as_view(),
    ),
    path(
        "organizations/<uuid:organization_id>/payment-accounts/<uuid:pk>/approve/",
        PaymentAccountApproveView.as_view(),
    ),
    path(
        "organizations/<uuid:organization_id>/payment-accounts/<uuid:pk>/versions/",
        PaymentAccountVersionCreateView.as_view(),
    ),
    path(
        "organizations/<uuid:organization_id>/payment-uploads/",
        PrivatePaymentUploadView.as_view(),
    ),
    path(
        "organizations/<uuid:organization_id>/payment-uploads/<uuid:upload_id>/download/",
        PrivatePaymentDownloadView.as_view(),
    ),
    path(
        "organizations/<uuid:organization_id>/payments/",
        PaymentListCreateView.as_view(),
    ),
    path(
        "organizations/<uuid:organization_id>/payments/<uuid:payment_id>/decision/",
        PaymentDecisionView.as_view(),
    ),
    path(
        "organizations/<uuid:organization_id>/refund-policy/",
        RefundPolicyView.as_view(),
    ),
    path(
        "organizations/<uuid:organization_id>/refunds/",
        RefundListCreateView.as_view(),
    ),
    path(
        "organizations/<uuid:organization_id>/refunds/<uuid:refund_id>/decision/",
        RefundDecisionView.as_view(),
    ),
    path(
        "organizations/<uuid:organization_id>/refunds/<uuid:refund_id>/paid/",
        RefundPaidView.as_view(),
    ),
    path(
        "organizations/<uuid:organization_id>/refunds/<uuid:refund_id>/complete/",
        RefundCompleteView.as_view(),
    ),
    path(
        "organizations/<uuid:organization_id>/corporate-invoices/"
        "<uuid:invoice_id>/payment-allocations/",
        InvoiceAllocationListView.as_view(),
    ),
    path(
        "organizations/<uuid:organization_id>/payment-connectors/",
        PaymentConnectorListCreateView.as_view(),
    ),
    path(
        "organizations/<uuid:organization_id>/payment-connectors/<uuid:pk>/",
        PaymentConnectorDetailView.as_view(),
    ),
    path(
        "organizations/<uuid:organization_id>/payment-connectors/"
        "<uuid:connector_id>/test/",
        PaymentConnectorTestView.as_view(),
    ),
    path(
        "organizations/<uuid:organization_id>/payment-connectors/"
        "<uuid:connector_id>/rotate/",
        PaymentConnectorRotateView.as_view(),
    ),
    path(
        "organizations/<uuid:organization_id>/payment-connectors/"
        "<uuid:connector_id>/disable/",
        PaymentConnectorDisableView.as_view(),
    ),
    path(
        "organizations/<uuid:organization_id>/provider-payment-intents/",
        ProviderPaymentIntentCreateView.as_view(),
    ),
    path(
        "public/payment-webhooks/<uuid:connector_id>/",
        PaymentConnectorWebhookView.as_view(),
    ),
]
