# Generated by Django 5.2.16 on 2026-07-25 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
        ('tenancy', '0010_seed_passenger_sales_boarding_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('boarding_type', models.CharField(choices=[('terminal', 'Terminal'), ('roadside', 'Roadside'), ('staff', 'Staff'), ('emergency', 'Emergency')], max_length=12)),
                ('method', models.CharField(choices=[('qr', 'QR scan'), ('barcode', 'Barcode'), ('manual_ticket', 'Manual ticket number'), ('passenger_search', 'Passenger search'), ('offline', 'Offline validation')], max_length=20)),
                ('status', models.CharField(choices=[('validated', 'Validated'), ('boarded', 'Boarded'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('no_show', 'No show')], max_length=12)),
                ('validated_at', models.DateTimeField()),
                ('boarded_at', models.DateTimeField(blank=True, null=True)),
                ('identity_confirmed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('offline', models.BooleanField(default=False)),
                ('client_event_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('boarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_boardings', to=settings.AUTH_USER_MODEL)),
                ('boarding_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boarding_records', to='network.routestop')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boarding_records', to='tenancy.organization')),
            ],
            options={
                'db_table': 'boarding_record',
            },
        ),
    ]
