# Generated by Django 5.2.16 on 2026-07-25 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boarding', '0001_initial'),
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingrecord',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boarding_records', to='passengers.passenger'),
        ),
    ]
