# Generated by Django 5.2.16 on 2026-07-25 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boarding', '0002_initial'),
        ('scheduling', '0002_trip_arrived_at_trip_boarding_started_at_and_more'),
        ('ticketing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='boardingrecord',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='boarding_record', to='ticketing.ticket'),
        ),
        migrations.AddField(
            model_name='boardingrecord',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boarding_records', to='scheduling.trip'),
        ),
        migrations.AddField(
            model_name='boardingrecord',
            name='validated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='validated_boardings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='boardingrecord',
            index=models.Index(fields=['trip', 'status'], name='boarding_trip_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='boardingrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['validated', 'boarded', 'completed'])), fields=('trip', 'passenger'), name='unique_active_boarding_per_trip_passenger'),
        ),
    ]
