# Generated by Django 5.2.16 on 2026-07-26 07:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0014_seed_notification_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('passenger', 'HBT Passenger'), ('business', 'HBT Business'), ('web', 'Website')], max_length=16)),
                ('category', models.CharField(choices=[('feature', 'Feature request'), ('usability', 'Usability'), ('bug', 'Bug'), ('service', 'Service'), ('security', 'Private security report'), ('other', 'Other')], max_length=16)),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField()),
                ('language', models.CharField(default='my', max_length=10)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('planned', 'Planned'), ('resolved', 'Resolved'), ('declined', 'Declined'), ('duplicate', 'Duplicate')], default='new', max_length=16)),
                ('priority', models.CharField(default='normal', max_length=16)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('device_context', models.JSONField(blank=True, default=dict)),
                ('owner_response', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_items', to='tenancy.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedback_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feedback_item',
                'indexes': [models.Index(fields=['organization', 'status', 'created_at'], name='feedback_org_status_idx')],
            },
        ),
    ]
