# Generated by Django 5.2.16 on 2026-07-26 08:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0016_seed_corporate_invoice_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name_my', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('description_my', models.TextField(blank=True)),
                ('description_en', models.TextField(blank=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('annual_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=5, max_digits=7)),
                ('entitlements', models.JSONField(default=dict)),
                ('limits', models.JSONField(default=dict)),
                ('contact_sales', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'subscriptions_plan',
                'ordering': ('display_order',),
                'constraints': [models.CheckConstraint(condition=models.Q(('monthly_price__gte', 0)), name='subscription_plan_monthly_nonnegative'), models.CheckConstraint(condition=models.Q(('annual_price__gte', 0)), name='subscription_plan_annual_nonnegative'), models.CheckConstraint(condition=models.Q(('tax_rate__gte', 0)), name='subscription_plan_tax_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='TenantSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('pending', 'Pending activation'), ('active', 'Active'), ('grace', 'Grace period'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=16)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=16)),
                ('starts_at', models.DateTimeField()),
                ('current_period_ends_at', models.DateTimeField()),
                ('grace_ends_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('entitlement_overrides', models.JSONField(blank=True, default=dict)),
                ('limit_overrides', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions_changed', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='subscription', to='tenancy.tenant')),
            ],
            options={
                'db_table': 'subscriptions_tenant_subscription',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('payment_submitted', 'Payment submitted'), ('paid', 'Paid'), ('void', 'Void'), ('overdue', 'Overdue')], default='draft', max_length=24)),
                ('currency', models.CharField(default='MMK', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=4, max_digits=7)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('period_starts_at', models.DateTimeField()),
                ('period_ends_at', models.DateTimeField()),
                ('due_at', models.DateTimeField()),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=160)),
                ('payment_evidence_note', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_invoices_created', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_invoices_verified', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='subscriptions.tenantsubscription')),
            ],
            options={
                'db_table': 'subscriptions_invoice',
            },
        ),
        migrations.AddIndex(
            model_name='tenantsubscription',
            index=models.Index(fields=['status', 'current_period_ends_at'], name='subscription_status_period_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioninvoice',
            index=models.Index(fields=['subscription', 'status', 'due_at'], name='subscription_invoice_due_idx'),
        ),
    ]
