# Generated by Django 5.2.16 on 2026-07-26 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_seed_public_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsubscription',
            name='scheduled_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_subscriptions', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantsubscription',
            name='suspension_reason',
            field=models.TextField(blank=True),
        ),
    ]
