# Generated by Django 5.2.16 on 2026-07-26 08:55

import apps.branding.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0016_seed_corporate_invoice_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationBranding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_slug', models.SlugField(max_length=120, unique=True)),
                ('name_my', models.CharField(max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('about_my', models.TextField(blank=True)),
                ('about_en', models.TextField(blank=True)),
                ('logo', models.FileField(blank=True, upload_to=apps.branding.models.branding_upload_path)),
                ('cover_image', models.FileField(blank=True, upload_to=apps.branding.models.branding_upload_path)),
                ('primary_color', models.CharField(default='#1F6FEB', max_length=7)),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('public_phone', models.CharField(blank=True, max_length=32)),
                ('public_email', models.EmailField(blank=True, max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='branding', to='tenancy.organization')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organization_branding_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'branding_organization',
                'indexes': [models.Index(fields=['is_published', 'is_verified'], name='branding_public_verified_idx')],
            },
        ),
    ]
