# Generated by Django 5.2.16 on 2026-07-26 04:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0013_seed_cargo_roadside_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installation_id', models.UUIDField(unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=16)),
                ('app_id', models.CharField(max_length=64)),
                ('app_version', models.CharField(max_length=32)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('replaced', 'Replaced')], default='active', max_length=16)),
                ('push_token', models.TextField(blank=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'offline_device',
            },
        ),
        migrations.CreateModel(
            name='AuthorizationSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permissions', models.JSONField(default=list)),
                ('scopes', models.JSONField(default=list)),
                ('issued_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='tenancy.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offline_authorization_snapshots', to='tenancy.organization')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorization_snapshots', to='offline.device')),
            ],
            options={
                'db_table': 'offline_authorization_snapshot',
            },
        ),
        migrations.CreateModel(
            name='SyncChange',
            fields=[
                ('sequence', models.BigAutoField(primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=80)),
                ('resource_id', models.UUIDField()),
                ('operation', models.CharField(max_length=16)),
                ('version', models.PositiveBigIntegerField(default=1)),
                ('payload', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_changes', to='tenancy.organization')),
            ],
            options={
                'db_table': 'offline_sync_change',
            },
        ),
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_operation_id', models.UUIDField()),
                ('operation_type', models.CharField(max_length=100)),
                ('payload_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('received', 'Received'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('conflict', 'Conflict')], default='received', max_length=16)),
                ('request_payload', models.JSONField(default=dict)),
                ('response_payload', models.JSONField(default=dict)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_operations', to='offline.device')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sync_operations', to='tenancy.organization')),
            ],
            options={
                'db_table': 'offline_sync_operation',
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['user', 'status'], name='offline_device_user_idx'),
        ),
        migrations.AddIndex(
            model_name='authorizationsnapshot',
            index=models.Index(fields=['device', 'organization', 'expires_at'], name='offline_auth_expiry_idx'),
        ),
        migrations.AddIndex(
            model_name='syncchange',
            index=models.Index(fields=['organization', 'sequence'], name='offline_change_cursor_idx'),
        ),
        migrations.AddIndex(
            model_name='syncoperation',
            index=models.Index(fields=['organization', 'created_at'], name='offline_operation_org_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncoperation',
            constraint=models.UniqueConstraint(fields=('device', 'client_operation_id'), name='unique_offline_device_operation'),
        ),
    ]
