# Generated by Django 5.2.16 on 2026-07-25 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0010_seed_passenger_sales_boarding_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passenger_code', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=255)),
                ('full_name_myanmar', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('infant', 'Infant'), ('senior', 'Senior citizen'), ('vip', 'VIP'), ('staff', 'Staff passenger')], default='adult', max_length=12)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('unspecified', 'Prefer not to say')], default='unspecified', max_length=12)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('national_id', models.CharField(blank=True, max_length=100)),
                ('passport_number', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=32)),
                ('travel_notes', models.TextField(blank=True)),
                ('special_assistance', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('active', 'Active'), ('archived', 'Archived')], default='registered', max_length=12)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passenger_profiles', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passengers', to='tenancy.organization')),
            ],
            options={
                'db_table': 'passengers_passenger',
                'indexes': [models.Index(fields=['organization', 'phone_number'], name='passenger_org_phone_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'passenger_code'), name='unique_passenger_code_per_org'), models.UniqueConstraint(condition=models.Q(('national_id', ''), _negated=True), fields=('organization', 'national_id'), name='unique_passenger_nrc_per_org'), models.UniqueConstraint(condition=models.Q(('passport_number', ''), _negated=True), fields=('organization', 'passport_number'), name='unique_passenger_passport_per_org')],
            },
        ),
    ]
