# Generated by Django 5.2.16 on 2026-07-26 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0003_passenger_managed_by'),
        ('reference_data', '0002_seed_nrc_reference_v1'),
        ('tenancy', '0017_seed_commercial_branding_media_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='passenger',
            name='unique_passenger_nrc_per_org',
        ),
        migrations.AddField(
            model_name='passenger',
            name='encrypted_nrc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='nrc_blind_index',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='passenger',
            name='nrc_citizenship_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passengers', to='reference_data.nrccitizenshiptype'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='nrc_serial',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='passenger',
            name='nrc_state_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passengers', to='reference_data.nrcstateregion'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='nrc_township',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='passengers', to='reference_data.nrctownship'),
        ),
        migrations.AddConstraint(
            model_name='passenger',
            constraint=models.UniqueConstraint(condition=models.Q(('nrc_blind_index', ''), _negated=True), fields=('organization', 'nrc_blind_index'), name='unique_passenger_nrc_blind_per_org'),
        ),
    ]
