# Generated by Django 5.2.16 on 2026-07-26 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0006_backfill_encrypted_nrc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='nrc_normalized',
        ),
    ]
