# Generated by Django 5.2.16 on 2026-07-25 07:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0002_initial'),
        ('cargo', '0001_initial'),
        ('tenancy', '0011_seed_cargo_finance_operations_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_number', models.CharField(max_length=64)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('wallet_qr', 'Wallet QR'), ('bank_transfer', 'Bank transfer'), ('corporate_credit', 'Corporate credit')], max_length=20)),
                ('status', models.CharField(choices=[('recorded', 'Recorded'), ('submitted', 'Awaiting verification'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='recorded', max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='MMK', max_length=3)),
                ('provider_name', models.CharField(blank=True, max_length=100)),
                ('transaction_reference', models.CharField(blank=True, max_length=255)),
                ('payer_reference', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('client_request_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to='bookings.booking')),
                ('cargo_shipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to='cargo.cargoshipment')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_payments', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to='tenancy.organization')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_payment_record',
                'constraints': [models.UniqueConstraint(fields=('organization', 'payment_number'), name='unique_payment_number_per_org'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_positive'), models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', False), ('cargo_shipment__isnull', True)), models.Q(('booking__isnull', True), ('cargo_shipment__isnull', False)), _connector='OR'), name='payment_exactly_one_business_target')],
            },
        ),
    ]
