# Generated by Django 5.2.16 on 2026-07-25 11:56

import apps.payments.models
import apps.payments.storage
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('payments', '0001_initial'),
        ('tenancy', '0011_seed_cargo_finance_operations_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceivingAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_code', models.SlugField()),
                ('account_type', models.CharField(choices=[('merchant', 'Merchant account'), ('personal', 'Approved personal wallet')], max_length=16)),
                ('provider_name', models.CharField(max_length=100)),
                ('account_name', models.CharField(max_length=150)),
                ('account_identifier', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('business_justification', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_payment_accounts', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.branch')),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.salescounter')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payment_accounts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_accounts', to='tenancy.organization')),
                ('terminal_operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.companyterminaloperation')),
            ],
            options={
                'db_table': 'payments_receiving_account',
            },
        ),
        migrations.CreateModel(
            name='PaymentReceivingAccountVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('display_label', models.CharField(max_length=150)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_until', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='payments.paymentreceivingaccount')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payment_account_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_receiving_account_version',
            },
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='receiving_account_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymentreceivingaccountversion'),
        ),
        migrations.CreateModel(
            name='PrivatePaymentUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('payment_evidence', 'Payment evidence'), ('account_qr', 'Receiving account QR')], max_length=24)),
                ('file', models.FileField(storage=apps.payments.storage.PrivatePaymentStorage(), upload_to=apps.payments.models.payment_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_uploads', to='tenancy.organization')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='private_payment_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_private_upload',
            },
        ),
        migrations.AddField(
            model_name='paymentreceivingaccountversion',
            name='qr_upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payments.privatepaymentupload'),
        ),
        migrations.CreateModel(
            name='PaymentEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_note', models.TextField(blank=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='payments.paymentrecord')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_payment_evidence', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_payment_evidence', to=settings.AUTH_USER_MODEL)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='payments.privatepaymentupload')),
            ],
            options={
                'db_table': 'payments_payment_evidence',
            },
        ),
        migrations.AddConstraint(
            model_name='paymentreceivingaccount',
            constraint=models.UniqueConstraint(fields=('organization', 'account_code'), name='unique_payment_account_code_per_org'),
        ),
        migrations.AddConstraint(
            model_name='paymentreceivingaccountversion',
            constraint=models.UniqueConstraint(fields=('account', 'version'), name='unique_payment_account_version'),
        ),
    ]
