# Generated by Django 5.2.16 on 2026-07-25 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_seatreservation_unique_active_seat_per_trip_and_more'),
        ('cargo', '0001_initial'),
        ('payments', '0002_paymentreceivingaccount_and_more'),
        ('tenancy', '0012_seed_payment_integration_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_reference', ''), _negated=True), fields=('organization', 'provider_name', 'transaction_reference'), name='unique_provider_payment_reference_per_org'),
        ),
    ]
