# Generated by Django 5.2.16 on 2026-07-26 11:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentrecord_unique_provider_payment_reference_per_org'),
        ('tenancy', '0018_seed_refund_reissue_permissions'),
        ('ticketing', '0002_ticket_replacement_of_ticket_revocation_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RefundPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('refund_window_hours', models.PositiveIntegerField(default=24)),
                ('refund_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('fixed_fee', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('approval_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('configured_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configured_refund_policies', to=settings.AUTH_USER_MODEL)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='refund_policy', to='tenancy.organization')),
            ],
            options={
                'db_table': 'payments_refund_policy',
                'constraints': [models.CheckConstraint(condition=models.Q(('refund_percentage__gte', 0), ('refund_percentage__lte', 100)), name='refund_percentage_between_zero_and_hundred'), models.CheckConstraint(condition=models.Q(('fixed_fee__gte', 0), ('approval_threshold__gte', 0)), name='refund_policy_amounts_nonnegative')],
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refund_number', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=16)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='MMK', max_length=3)),
                ('reason', models.TextField()),
                ('policy_snapshot', models.JSONField(default=dict)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_reason', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payout_reference', models.CharField(blank=True, max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client_request_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds_decided', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to='tenancy.organization')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds_paid', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to='payments.paymentrecord')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds_requested', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund_requests', to='ticketing.ticket')),
            ],
            options={
                'db_table': 'payments_refund_request',
                'constraints': [models.UniqueConstraint(fields=('organization', 'refund_number'), name='unique_refund_number_per_org'), models.CheckConstraint(condition=models.Q(('requested_amount__gt', 0)), name='refund_requested_amount_positive'), models.CheckConstraint(condition=models.Q(('approved_amount__isnull', True), ('approved_amount__gt', 0), _connector='OR'), name='refund_approved_amount_positive_or_null'), models.UniqueConstraint(condition=models.Q(('payout_reference', ''), _negated=True), fields=('organization', 'payout_reference'), name='unique_refund_payout_reference_per_org')],
            },
        ),
    ]
