# Generated by Django 5.2.16 on 2026-07-26 12:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_corporatecustomer_corporatebookingapproval_and_more'),
        ('cargo', '0009_remove_cargocontact_nrc_normalized'),
        ('payments', '0004_refundpolicy_refundrequest'),
        ('tenancy', '0019_seed_provider_payment_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePaymentAllocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'db_table': 'payments_invoice_allocation',
            },
        ),
        migrations.CreateModel(
            name='PaymentConnector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField()),
                ('adapter', models.CharField(max_length=100)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('disabled', 'Disabled')], default='draft', max_length=16)),
                ('merchant_id', models.CharField(max_length=255)),
                ('encrypted_credentials', models.TextField()),
                ('webhook_secret_encrypted', models.TextField()),
                ('credential_version', models.PositiveIntegerField(default=1)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_succeeded', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'payments_connector',
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('requires_reconciliation', 'Requires reconciliation')], default='created', max_length=32)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('checkout_payload', models.JSONField(default=dict)),
                ('last_error_code', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'payments_intent',
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('duplicate', 'Duplicate'), ('quarantined', 'Quarantined')], default='received', max_length=16)),
                ('payload_sha256', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('reason', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'payments_webhook_event',
            },
        ),
        migrations.RemoveConstraint(
            model_name='paymentrecord',
            name='payment_exactly_one_business_target',
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='corporate_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to='bookings.corporateinvoice'),
        ),
        migrations.AddConstraint(
            model_name='paymentrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('booking__isnull', False), ('cargo_shipment__isnull', True), ('corporate_invoice__isnull', True)), models.Q(('booking__isnull', True), ('cargo_shipment__isnull', False), ('corporate_invoice__isnull', True)), models.Q(('booking__isnull', True), ('cargo_shipment__isnull', True), ('corporate_invoice__isnull', False)), _connector='OR'), name='payment_exactly_one_business_target'),
        ),
        migrations.AddField(
            model_name='invoicepaymentallocation',
            name='allocated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_payment_allocations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicepaymentallocation',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='bookings.corporateinvoice'),
        ),
        migrations.AddField(
            model_name='invoicepaymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_allocations', to='payments.paymentrecord'),
        ),
        migrations.AddField(
            model_name='paymentconnector',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_payment_connectors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentconnector',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_connectors', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='payments.paymentconnector'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='tenancy.organization'),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='provider_intent', to='payments.paymentrecord'),
        ),
        migrations.AddField(
            model_name='paymentwebhookevent',
            name='connector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='webhook_events', to='payments.paymentconnector'),
        ),
        migrations.AddConstraint(
            model_name='invoicepaymentallocation',
            constraint=models.UniqueConstraint(fields=('invoice', 'payment'), name='unique_invoice_payment_allocation'),
        ),
        migrations.AddConstraint(
            model_name='invoicepaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='invoice_allocation_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentconnector',
            constraint=models.UniqueConstraint(fields=('organization', 'code', 'environment'), name='unique_payment_connector_environment'),
        ),
        migrations.AddConstraint(
            model_name='paymentwebhookevent',
            constraint=models.UniqueConstraint(fields=('connector', 'event_id'), name='unique_connector_webhook_event'),
        ),
    ]
