# Generated by Django 5.2.16 on 2026-07-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_invoicepaymentallocation_paymentconnector_and_more'),
        ('tenancy', '0019_seed_provider_payment_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='last_reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='next_reconcile_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='reconciliation_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymentintent',
            name='reconciliation_error',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['status', 'next_reconcile_at'], name='payment_intent_reconcile_idx'),
        ),
    ]
