# Generated by Django 5.2.16 on 2026-08-01 05:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_seatlock'),
        ('cargo', '0009_remove_cargocontact_nrc_normalized'),
        ('payments', '0006_paymentintent_last_reconciled_at_and_more'),
        ('tenancy', '0019_seed_provider_payment_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='paymentrecord',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='payment_org_status_date_idx'),
        ),
    ]
