# Generated by Django 5.2.16 on 2026-07-25 05:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('network', '0001_initial'),
        ('tenancy', '0007_seed_fleet_workforce_permissions'),
        ('workforce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=255)),
                ('planned_departure_time', models.TimeField()),
                ('planned_arrival_time', models.TimeField()),
                ('arrival_day_offset', models.PositiveSmallIntegerField(default=0)),
                ('operating_days', models.JSONField(default=list)),
                ('effective_from', models.DateField()),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('operates_on_public_holidays', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('approved', 'Approved'), ('operational', 'Operational'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='tenancy.organization')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='network.route')),
            ],
            options={
                'db_table': 'scheduling_schedule',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trip_number', models.CharField(max_length=50)),
                ('service_date', models.DateField()),
                ('planned_departure_at', models.DateTimeField()),
                ('planned_arrival_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ready', 'Ready'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('in_progress', 'In progress'), ('delayed', 'Delayed'), ('interrupted', 'Interrupted'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], default='planned', max_length=16)),
                ('operational_notes', models.TextField(blank=True)),
                ('schedule_snapshot', models.JSONField(blank=True, default=dict)),
                ('route_snapshot', models.JSONField(blank=True, default=dict)),
                ('seat_layout_snapshot', models.JSONField(blank=True, default=dict)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_trips', to='workforce.conductorprofile')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_trips', to='workforce.driverprofile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='tenancy.organization')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='network.route')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='scheduling.schedule')),
                ('seat_layout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_snapshots', to='fleet.seatlayout')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_trips', to='fleet.vehicle')),
            ],
            options={
                'db_table': 'scheduling_trip',
            },
        ),
        migrations.CreateModel(
            name='TripAssignmentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_type', models.CharField(choices=[('vehicle', 'Vehicle'), ('driver', 'Driver'), ('conductor', 'Conductor')], max_length=12)),
                ('previous_resource_id', models.UUIDField(blank=True, null=True)),
                ('resource_id', models.UUIDField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_assignment_events', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignment_events', to='scheduling.trip')),
            ],
            options={
                'db_table': 'scheduling_trip_assignment_event',
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['organization', 'status'], name='schedule_org_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('organization', 'code', 'version'), name='unique_schedule_code_version'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['organization', 'service_date', 'status'], name='trip_org_date_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(fields=('organization', 'trip_number'), name='unique_trip_number_per_org'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule__isnull', False)), fields=('schedule', 'service_date'), name='unique_schedule_trip_per_service_date'),
        ),
    ]
