# Generated by Django 5.2.16 on 2026-07-25 06:19

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
        ('scheduling', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='boarding_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='current_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_trips', to='network.routestop'),
        ),
        migrations.AddField(
            model_name='trip',
            name='departed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TripOperationalEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('ready', 'Trip ready'), ('boarding_started', 'Boarding started'), ('departed', 'Departed'), ('en_route', 'En route'), ('stop_reached', 'Stop reached'), ('arrived', 'Arrived')], max_length=20)),
                ('from_status', models.CharField(choices=[('planned', 'Planned'), ('ready', 'Ready'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('in_progress', 'In progress'), ('delayed', 'Delayed'), ('interrupted', 'Interrupted'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], max_length=16)),
                ('to_status', models.CharField(choices=[('planned', 'Planned'), ('ready', 'Ready'), ('boarding', 'Boarding'), ('departed', 'Departed'), ('in_progress', 'In progress'), ('delayed', 'Delayed'), ('interrupted', 'Interrupted'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], max_length=16)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('offline', models.BooleanField(default=False)),
                ('client_event_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip_operational_events', to=settings.AUTH_USER_MODEL)),
                ('route_stop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trip_operational_events', to='network.routestop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operational_events', to='scheduling.trip')),
            ],
            options={
                'db_table': 'scheduling_trip_operational_event',
                'ordering': ('occurred_at', 'created_at'),
                'indexes': [models.Index(fields=['trip', 'event_type', 'occurred_at'], name='trip_event_type_time_idx')],
            },
        ),
    ]
