# Generated by Django 5.2.16 on 2026-07-26 16:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_platformaccessgrant'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(choices=[('access', 'Access'), ('correction', 'Correction'), ('export', 'Export'), ('deletion', 'Deletion'), ('restriction', 'Restriction')], max_length=16)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Identity verified'), ('in_progress', 'In progress'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='submitted', max_length=16)),
                ('details', models.TextField(blank=True)),
                ('jurisdiction', models.CharField(default='MM', max_length=8)),
                ('due_at', models.DateTimeField()),
                ('verification_method', models.CharField(blank=True, max_length=80)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('retention_hold', models.BooleanField(default=False)),
                ('retention_reason', models.TextField(blank=True)),
                ('response_summary', models.TextField(blank=True)),
                ('evidence_reference', models.CharField(blank=True, max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='privacy_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='privacy_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'identity_data_subject_request',
                'indexes': [models.Index(fields=['status', 'due_at'], name='privacy_status_due_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['submitted', 'verified', 'in_progress'])), fields=('user', 'request_type'), name='unique_active_privacy_request_type_per_user'), models.CheckConstraint(condition=models.Q(models.Q(('retention_hold', False), ('retention_reason', '')), ('retention_hold', True), _connector='OR'), name='privacy_retention_reason_only_with_hold')],
            },
        ),
    ]
